/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package com.other.avro;
@org.apache.avro.specific.AvroGenerated
public enum Color implements org.apache.avro.generic.GenericEnumSymbol<Color> {
  RED, GREEN, BLUE  ;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"enum\",\"name\":\"Color\",\"namespace\":\"com.other.avro\",\"symbols\":[\"RED\",\"GREEN\",\"BLUE\"]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  @Override
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
}
