/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package com.other.avro;

import org.apache.avro.specific.SpecificData;
import org.apache.avro.util.Utf8;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.SchemaStore;

@org.apache.avro.specific.AvroGenerated
public class Figure extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = -7454487485553637135L;


  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"Figure\",\"namespace\":\"com.other.avro\",\"fields\":[{\"name\":\"id\",\"type\":\"int\"},{\"name\":\"points\",\"type\":{\"type\":\"array\",\"items\":{\"type\":\"record\",\"name\":\"Point\",\"fields\":[{\"name\":\"x\",\"type\":\"int\"},{\"name\":\"y\",\"type\":\"int\"}]}}},{\"name\":\"color\",\"type\":{\"type\":\"enum\",\"name\":\"Color\",\"symbols\":[\"RED\",\"GREEN\",\"BLUE\"]}}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static final SpecificData MODEL$ = new SpecificData();

  private static final BinaryMessageEncoder<Figure> ENCODER =
      new BinaryMessageEncoder<>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<Figure> DECODER =
      new BinaryMessageDecoder<>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageEncoder instance used by this class.
   * @return the message encoder used by this class
   */
  public static BinaryMessageEncoder<Figure> getEncoder() {
    return ENCODER;
  }

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   * @return the message decoder used by this class
   */
  public static BinaryMessageDecoder<Figure> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   * @return a BinaryMessageDecoder instance for this class backed by the given SchemaStore
   */
  public static BinaryMessageDecoder<Figure> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<>(MODEL$, SCHEMA$, resolver);
  }

  /**
   * Serializes this Figure to a ByteBuffer.
   * @return a buffer holding the serialized data for this instance
   * @throws java.io.IOException if this instance could not be serialized
   */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /**
   * Deserializes a Figure from a ByteBuffer.
   * @param b a byte buffer holding serialized data for an instance of this class
   * @return a Figure instance decoded from the given buffer
   * @throws java.io.IOException if the given bytes could not be deserialized into an instance of this class
   */
  public static Figure fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

  private int id;
  private java.util.List<com.other.avro.Point> points;
  private com.other.avro.Color color;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public Figure() {}

  /**
   * All-args constructor.
   * @param id The new value for id
   * @param points The new value for points
   * @param color The new value for color
   */
  public Figure(java.lang.Integer id, java.util.List<com.other.avro.Point> points, com.other.avro.Color color) {
    this.id = id;
    this.points = points;
    this.color = color;
  }

  @Override
  public org.apache.avro.specific.SpecificData getSpecificData() { return MODEL$; }

  @Override
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }

  // Used by DatumWriter.  Applications should not call.
  @Override
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return id;
    case 1: return points;
    case 2: return color;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  // Used by DatumReader.  Applications should not call.
  @Override
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: id = (java.lang.Integer)value$; break;
    case 1: points = (java.util.List<com.other.avro.Point>)value$; break;
    case 2: color = (com.other.avro.Color)value$; break;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  /**
   * Gets the value of the 'id' field.
   * @return The value of the 'id' field.
   */
  public int getId() {
    return id;
  }


  /**
   * Sets the value of the 'id' field.
   * @param value the value to set.
   */
  public void setId(int value) {
    this.id = value;
  }

  /**
   * Gets the value of the 'points' field.
   * @return The value of the 'points' field.
   */
  public java.util.List<com.other.avro.Point> getPoints() {
    return points;
  }


  /**
   * Sets the value of the 'points' field.
   * @param value the value to set.
   */
  public void setPoints(java.util.List<com.other.avro.Point> value) {
    this.points = value;
  }

  /**
   * Gets the value of the 'color' field.
   * @return The value of the 'color' field.
   */
  public com.other.avro.Color getColor() {
    return color;
  }


  /**
   * Sets the value of the 'color' field.
   * @param value the value to set.
   */
  public void setColor(com.other.avro.Color value) {
    this.color = value;
  }

  /**
   * Creates a new Figure RecordBuilder.
   * @return A new Figure RecordBuilder
   */
  public static com.other.avro.Figure.Builder newBuilder() {
    return new com.other.avro.Figure.Builder();
  }

  /**
   * Creates a new Figure RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new Figure RecordBuilder
   */
  public static com.other.avro.Figure.Builder newBuilder(com.other.avro.Figure.Builder other) {
    if (other == null) {
      return new com.other.avro.Figure.Builder();
    } else {
      return new com.other.avro.Figure.Builder(other);
    }
  }

  /**
   * Creates a new Figure RecordBuilder by copying an existing Figure instance.
   * @param other The existing instance to copy.
   * @return A new Figure RecordBuilder
   */
  public static com.other.avro.Figure.Builder newBuilder(com.other.avro.Figure other) {
    if (other == null) {
      return new com.other.avro.Figure.Builder();
    } else {
      return new com.other.avro.Figure.Builder(other);
    }
  }

  /**
   * RecordBuilder for Figure instances.
   */
  @org.apache.avro.specific.AvroGenerated
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<Figure>
    implements org.apache.avro.data.RecordBuilder<Figure> {

    private int id;
    private java.util.List<com.other.avro.Point> points;
    private com.other.avro.Color color;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$, MODEL$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(com.other.avro.Figure.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.id)) {
        this.id = data().deepCopy(fields()[0].schema(), other.id);
        fieldSetFlags()[0] = other.fieldSetFlags()[0];
      }
      if (isValidValue(fields()[1], other.points)) {
        this.points = data().deepCopy(fields()[1].schema(), other.points);
        fieldSetFlags()[1] = other.fieldSetFlags()[1];
      }
      if (isValidValue(fields()[2], other.color)) {
        this.color = data().deepCopy(fields()[2].schema(), other.color);
        fieldSetFlags()[2] = other.fieldSetFlags()[2];
      }
    }

    /**
     * Creates a Builder by copying an existing Figure instance
     * @param other The existing instance to copy.
     */
    private Builder(com.other.avro.Figure other) {
      super(SCHEMA$, MODEL$);
      if (isValidValue(fields()[0], other.id)) {
        this.id = data().deepCopy(fields()[0].schema(), other.id);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.points)) {
        this.points = data().deepCopy(fields()[1].schema(), other.points);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.color)) {
        this.color = data().deepCopy(fields()[2].schema(), other.color);
        fieldSetFlags()[2] = true;
      }
    }

    /**
      * Gets the value of the 'id' field.
      * @return The value.
      */
    public int getId() {
      return id;
    }


    /**
      * Sets the value of the 'id' field.
      * @param value The value of 'id'.
      * @return This builder.
      */
    public com.other.avro.Figure.Builder setId(int value) {
      validate(fields()[0], value);
      this.id = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'id' field has been set.
      * @return True if the 'id' field has been set, false otherwise.
      */
    public boolean hasId() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'id' field.
      * @return This builder.
      */
    public com.other.avro.Figure.Builder clearId() {
      fieldSetFlags()[0] = false;
      return this;
    }

    /**
      * Gets the value of the 'points' field.
      * @return The value.
      */
    public java.util.List<com.other.avro.Point> getPoints() {
      return points;
    }


    /**
      * Sets the value of the 'points' field.
      * @param value The value of 'points'.
      * @return This builder.
      */
    public com.other.avro.Figure.Builder setPoints(java.util.List<com.other.avro.Point> value) {
      validate(fields()[1], value);
      this.points = value;
      fieldSetFlags()[1] = true;
      return this;
    }

    /**
      * Checks whether the 'points' field has been set.
      * @return True if the 'points' field has been set, false otherwise.
      */
    public boolean hasPoints() {
      return fieldSetFlags()[1];
    }


    /**
      * Clears the value of the 'points' field.
      * @return This builder.
      */
    public com.other.avro.Figure.Builder clearPoints() {
      points = null;
      fieldSetFlags()[1] = false;
      return this;
    }

    /**
      * Gets the value of the 'color' field.
      * @return The value.
      */
    public com.other.avro.Color getColor() {
      return color;
    }


    /**
      * Sets the value of the 'color' field.
      * @param value The value of 'color'.
      * @return This builder.
      */
    public com.other.avro.Figure.Builder setColor(com.other.avro.Color value) {
      validate(fields()[2], value);
      this.color = value;
      fieldSetFlags()[2] = true;
      return this;
    }

    /**
      * Checks whether the 'color' field has been set.
      * @return True if the 'color' field has been set, false otherwise.
      */
    public boolean hasColor() {
      return fieldSetFlags()[2];
    }


    /**
      * Clears the value of the 'color' field.
      * @return This builder.
      */
    public com.other.avro.Figure.Builder clearColor() {
      color = null;
      fieldSetFlags()[2] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public Figure build() {
      try {
        Figure record = new Figure();
        record.id = fieldSetFlags()[0] ? this.id : (java.lang.Integer) defaultValue(fields()[0]);
        record.points = fieldSetFlags()[1] ? this.points : (java.util.List<com.other.avro.Point>) defaultValue(fields()[1]);
        record.color = fieldSetFlags()[2] ? this.color : (com.other.avro.Color) defaultValue(fields()[2]);
        return record;
      } catch (org.apache.avro.AvroMissingFieldException e) {
        throw e;
      } catch (java.lang.Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<Figure>
    WRITER$ = (org.apache.avro.io.DatumWriter<Figure>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<Figure>
    READER$ = (org.apache.avro.io.DatumReader<Figure>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

  @Override protected boolean hasCustomCoders() { return true; }

  @Override public void customEncode(org.apache.avro.io.Encoder out)
    throws java.io.IOException
  {
    out.writeInt(this.id);

    long size0 = this.points.size();
    out.writeArrayStart();
    out.setItemCount(size0);
    long actualSize0 = 0;
    for (com.other.avro.Point e0: this.points) {
      actualSize0++;
      out.startItem();
      e0.customEncode(out);
    }
    out.writeArrayEnd();
    if (actualSize0 != size0)
      throw new java.util.ConcurrentModificationException("Array-size written was " + size0 + ", but element count was " + actualSize0 + ".");

    out.writeEnum(this.color.ordinal());

  }

  @Override public void customDecode(org.apache.avro.io.ResolvingDecoder in)
    throws java.io.IOException
  {
    org.apache.avro.Schema.Field[] fieldOrder = in.readFieldOrderIfDiff();
    if (fieldOrder == null) {
      this.id = in.readInt();

      long size0 = in.readArrayStart();
      java.util.List<com.other.avro.Point> a0 = this.points;
      if (a0 == null) {
        a0 = new SpecificData.Array<com.other.avro.Point>((int)size0, SCHEMA$.getField("points").schema());
        this.points = a0;
      } else a0.clear();
      SpecificData.Array<com.other.avro.Point> ga0 = (a0 instanceof SpecificData.Array ? (SpecificData.Array<com.other.avro.Point>)a0 : null);
      for ( ; 0 < size0; size0 = in.arrayNext()) {
        for ( ; size0 != 0; size0--) {
          com.other.avro.Point e0 = (ga0 != null ? ga0.peek() : null);
          if (e0 == null) {
            e0 = new com.other.avro.Point();
          }
          e0.customDecode(in);
          a0.add(e0);
        }
      }

      this.color = com.other.avro.Color.values()[in.readEnum()];

    } else {
      for (int i = 0; i < 3; i++) {
        switch (fieldOrder[i].pos()) {
        case 0:
          this.id = in.readInt();
          break;

        case 1:
          long size0 = in.readArrayStart();
          java.util.List<com.other.avro.Point> a0 = this.points;
          if (a0 == null) {
            a0 = new SpecificData.Array<com.other.avro.Point>((int)size0, SCHEMA$.getField("points").schema());
            this.points = a0;
          } else a0.clear();
          SpecificData.Array<com.other.avro.Point> ga0 = (a0 instanceof SpecificData.Array ? (SpecificData.Array<com.other.avro.Point>)a0 : null);
          for ( ; 0 < size0; size0 = in.arrayNext()) {
            for ( ; size0 != 0; size0--) {
              com.other.avro.Point e0 = (ga0 != null ? ga0.peek() : null);
              if (e0 == null) {
                e0 = new com.other.avro.Point();
              }
              e0.customDecode(in);
              a0.add(e0);
            }
          }
          break;

        case 2:
          this.color = com.other.avro.Color.values()[in.readEnum()];
          break;

        default:
          throw new java.io.IOException("Corrupt ResolvingDecoder.");
        }
      }
    }
  }
}










